//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GanGao.Data.DTO {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GanGao.Data.DTO.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 下级部门 的本地化字符串。
        /// </summary>
        internal static string DepartmentChilds {
            get {
                return ResourceManager.GetString("DepartmentChilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门名称 的本地化字符串。
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级部门 的本地化字符串。
        /// </summary>
        internal static string DepartmentParent {
            get {
                return ResourceManager.GetString("DepartmentParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门角色 的本地化字符串。
        /// </summary>
        internal static string DepartmentRole {
            get {
                return ResourceManager.GetString("DepartmentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作名称 的本地化字符串。
        /// </summary>
        internal static string PermissionActionName {
            get {
                return ResourceManager.GetString("PermissionActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器名称 的本地化字符串。
        /// </summary>
        internal static string PermissionControllerName {
            get {
                return ResourceManager.GetString("PermissionControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限部门 的本地化字符串。
        /// </summary>
        internal static string PermissionDepartments {
            get {
                return ResourceManager.GetString("PermissionDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数类型 的本地化字符串。
        /// </summary>
        internal static string PermissionParameters {
            get {
                return ResourceManager.GetString("PermissionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属部门 的本地化字符串。
        /// </summary>
        internal static string UserDepartments {
            get {
                return ResourceManager.GetString("UserDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户邮箱 的本地化字符串。
        /// </summary>
        internal static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证号 的本地化字符串。
        /// </summary>
        internal static string UserIdCard {
            get {
                return ResourceManager.GetString("UserIdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户昵称 的本地化字符串。
        /// </summary>
        internal static string UserNick {
            get {
                return ResourceManager.GetString("UserNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号 的本地化字符串。
        /// </summary>
        internal static string UserPhoneNumber {
            get {
                return ResourceManager.GetString("UserPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string UserTrueName {
            get {
                return ResourceManager.GetString("UserTrueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信 的本地化字符串。
        /// </summary>
        internal static string UserWX {
            get {
                return ResourceManager.GetString("UserWX", resourceCulture);
            }
        }
    }
}
