//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuDong.DAL.UnitOfWorks {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuDong.DAL.UnitOfWorks.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 提交数据更新时发生异常：{0} 的本地化字符串。
        /// </summary>
        internal static string CommitDataError {
            get {
                return ResourceManager.GetString("CommitDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接数据库超时，请检查网络连接或者数据库服务器是否正常。 的本地化字符串。
        /// </summary>
        internal static string ConnTimeOut {
            get {
                return ResourceManager.GetString("ConnTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所连接的数据库无效。 的本地化字符串。
        /// </summary>
        internal static string DataBaseInvalid {
            get {
                return ResourceManager.GetString("DataBaseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用设定的用户名与密码登录数据库失败。 的本地化字符串。
        /// </summary>
        internal static string DataBaseUserPasswordError {
            get {
                return ResourceManager.GetString("DataBaseUserPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体映射对象个数为0，创建DbContext上下文对象失败。 的本地化字符串。
        /// </summary>
        internal static string EntityMappersIsZero {
            get {
                return ResourceManager.GetString("EntityMappersIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外键约束，无法保存数据的变更。 的本地化字符串。
        /// </summary>
        internal static string ForeignKeyNoSaveData {
            get {
                return ResourceManager.GetString("ForeignKeyNoSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主键重复，无法插入数据。 的本地化字符串。
        /// </summary>
        internal static string KeyNoInsert {
            get {
                return ResourceManager.GetString("KeyNoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SqlServer服务不存在或拒绝访问。 的本地化字符串。
        /// </summary>
        internal static string ServerNotExist {
            get {
                return ResourceManager.GetString("ServerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SqlServer服务已暂停，不能提供数据服务。 的本地化字符串。
        /// </summary>
        internal static string ServerStop {
            get {
                return ResourceManager.GetString("ServerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定存储过程不存在。 的本地化字符串。
        /// </summary>
        internal static string StoreNotExist {
            get {
                return ResourceManager.GetString("StoreNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定名称的表不存在。 的本地化字符串。
        /// </summary>
        internal static string TableNotExist {
            get {
                return ResourceManager.GetString("TableNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误。 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
